Somehow needed to add 'libopencv_java.so' to make it work compile (I should fixed in another way). The error I was getting was:
[...]/OpenCV-2.4.7-android-sdk/sdk/native/libs/armeabi-v7a//libopencv_imgproc.a(templmatch.cpp.o):templmatch.cpp:function cv::crossCorr(cv::Mat const&, cv::Mat const&, cv::Mat&, cv::Size_<int>, int, cv::Point_<int>, double, int): error: undefined reference to 'cv::getOptimalDFTSize(int)'

Note: I have symbolic links to the .so libraries inside the Qt5 folder (Qt5.2.0/5.2.0-beta1/android_armv7/lib)